import { PT_Serif } from "next/font/google";
import NavBar from "@/components/NavBar";
import "@/styles/globals.css";

const ptSerif = PT_Serif({
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${ptSerif.className}`}>
        <NavBar/>
        {children}
      </body>
    </html>
  );
}
